"""Seed script to populate the ConstruyeSeguro video library."""
from __future__ import annotations

from backend import database

VIDEO_DATA = [
    {
        "title": "Cómo se empieza una casa desde cero ?",
        "category": "cimientos",
        "youtube_id": "NB8iiS8isFk",
        "level": "principiante",
        "stage": "Preparación del terreno y cimientos",
        "description": "Recorrido por el despalme y la limpieza del terreno antes de cimentar.",
        "manual_step": "preparacion_terreno",
        "tags": "despalme,terreno,drenaje",
    },
    {
        "title": "Construcción de una casa paso a paso, aprende fácil",
        "category": "estructura",
        "youtube_id": "KQ0hWpgF4JM",
        "level": "principiante",
        "stage": "Muros y estructura",
        "description": "Resumen accesible de cada fase constructiva desde la excavación hasta la losa.",
        "manual_step": "levantamiento_muros",
        "tags": "estructura,paso a paso",
    },
    {
        "title": "Cómo Construir una Casa en 7 pasos desde cero",
        "category": "planificacion",
        "youtube_id": "AogF87ts858",
        "level": "principiante",
        "stage": "Aprendizaje complementario",
        "description": "Los siete hitos principales para levantar una vivienda familiar.",
        "manual_step": "preparacion_terreno",
        "tags": "planificacion,cronograma",
    },
    {
        "title": "CONSTRUCCIÓN de CASA desde CERO | BITÁCORA de OBRA",
        "category": "planificacion",
        "youtube_id": "MLsGNyqMIzs",
        "level": "principiante",
        "stage": "Aprendizaje complementario",
        "description": "Bitácora de obra que documenta decisiones clave semana a semana.",
        "manual_step": "levantamiento_muros",
        "tags": "bitacora,control",
    },
    {
        "title": "Como construir una CASA DESDE CERO !! Trazo y Excavación",
        "category": "cimientos",
        "youtube_id": "AQNA2J1GKl8",
        "level": "principiante",
        "stage": "Preparación del terreno y cimientos",
        "description": "Trazado, replanteo y excavación seguros para zapatas corridas.",
        "manual_step": "preparacion_terreno",
        "tags": "trazo,excavacion",
    },
    {
        "title": "¡Cómo construir una casa explicado PASO A PASO! #CIMENTACIÓN #REPLANTEO",
        "category": "cimientos",
        "youtube_id": "S6h6nI6T4fk",
        "level": "intermedio",
        "stage": "Preparación del terreno y cimientos",
        "description": "Detalle del replanteo, armado de acero y colado de la cimentación.",
        "manual_step": "preparacion_terreno",
        "tags": "cimentacion,replanteo",
    },
    {
        "title": "House construction process step by step",
        "category": "estructura",
        "youtube_id": "r-thd4PJKBw",
        "level": "intermedio",
        "stage": "Muros y estructura",
        "description": "De la losa al techo: cada fase constructiva con animaciones claras.",
        "manual_step": "levantamiento_muros",
        "tags": "muros,losa",
    },
    {
        "title": "How a House is Built | Most Comprehensive Video EVER …",
        "category": "estructura",
        "youtube_id": "W4YozokJjOA",
        "level": "intermedio",
        "stage": "Muros y estructura",
        "description": "Explicación detallada de estructura, instalaciones y acabados.",
        "manual_step": "instalaciones_seguras",
        "tags": "estructura,instalaciones",
    },
    {
        "title": "¿COMO se CONSTRUYEN casas en ESTADOS UNIDOS …",
        "category": "estructura",
        "youtube_id": "5fOmcEDOTv0",
        "level": "intermedio",
        "stage": "Muros y estructura",
        "description": "Comparativa de sistemas constructivos ligeros y tradicional.",
        "manual_step": "levantamiento_muros",
        "tags": "madera,estructura ligera",
    },
    {
        "title": "Inexpensive house in 10 days. Full construction process",
        "category": "planificacion",
        "youtube_id": "SL0l1rDKF6Y",
        "level": "intermedio",
        "stage": "Aprendizaje complementario",
        "description": "Cronología acelerada de una vivienda económica con tips de logística.",
        "manual_step": "preparacion_terreno",
        "tags": "logistica,rapidez",
    },
    {
        "title": "ALL 50 STEPS How to Build a House from Start to Finish",
        "category": "planificacion",
        "youtube_id": "5mY-T2r_O8",
        "level": "avanzado",
        "stage": "Aprendizaje complementario",
        "description": "Guía completa con los 50 hitos del proceso constructivo profesional.",
        "manual_step": "acabados_finales",
        "tags": "checklist,proceso",
    },
    {
        "title": "Building A House in 9 Minutes!",
        "category": "planificacion",
        "youtube_id": "M-MlVkQybjI",
        "level": "avanzado",
        "stage": "Aprendizaje complementario",
        "description": "Visualización acelerada de toda la obra con énfasis en coordinación.",
        "manual_step": "levantamiento_muros",
        "tags": "timelapse,coordinacion",
    },
    {
        "title": "Building A House Start To Finish In 7 Days!",
        "category": "planificacion",
        "youtube_id": "QgMGZLm5_38",
        "level": "avanzado",
        "stage": "Aprendizaje complementario",
        "description": "Estrategia de cuadrillas y logística para levantar una casa en una semana.",
        "manual_step": "instalaciones_seguras",
        "tags": "logistica,coordinacion",
    },
    {
        "title": "Building A House Start To Finish – Playlist",
        "category": "planificacion",
        "youtube_id": "videoseries?list=PL8XEQ1XKYNDU28EZTqiP_qMo3kriBsnMk",
        "level": "avanzado",
        "stage": "Aprendizaje complementario",
        "description": "Serie completa con capítulos dedicados a cada sistema constructivo.",
        "manual_step": "instalaciones_seguras",
        "tags": "playlist,planificacion",
    },
    {
        "title": "The most comprehensive new home construction video …",
        "category": "planificacion",
        "youtube_id": "videoseries?list=PL8pCuSjragkDP-S1e4T9pPnDordMrEtLX",
        "level": "avanzado",
        "stage": "Aprendizaje complementario",
        "description": "Playlist profesional con capítulos sobre cimentación, instalaciones y acabados.",
        "manual_step": "acabados_finales",
        "tags": "playlist,profesional",
    },
    {
        "title": "Step By Step: Building a House | Part 1",
        "category": "estructura",
        "youtube_id": "rC8QzPRlFTs",
        "level": "avanzado",
        "stage": "Muros y estructura",
        "description": "Primer capítulo de una serie técnica orientada a autoconstructores avanzados.",
        "manual_step": "levantamiento_muros",
        "tags": "serie,estructura",
    },
    {
        "title": "How to Build a House in 10 Steps: A Practical and Easy-to-Follow Guide",
        "category": "planificacion",
        "youtube_id": "oH0Hln105vI",
        "level": "avanzado",
        "stage": "Aprendizaje complementario",
        "description": "Resumen ejecutivo con recomendaciones de seguridad y control de calidad.",
        "manual_step": "instalaciones_seguras",
        "tags": "seguridad,control",
    },
    {
        "title": "¿Cómo construir una casa paso a paso desde la cimentación ...",
        "category": "cimientos",
        "youtube_id": "Z9fxrs45wi8",
        "level": "avanzado",
        "stage": "Preparación del terreno y cimientos",
        "description": "Tutorial técnico de cimentación con recomendaciones para suelos húmedos.",
        "manual_step": "preparacion_terreno",
        "tags": "cimentacion,humedad",
    },
    {
        "title": "Así Se Construye Una CASA Desde Cero En USA",
        "category": "estructura",
        "youtube_id": "3mQWLV-QvqY",
        "level": "avanzado",
        "stage": "Muros y estructura",
        "description": "Secuencia completa con énfasis en estructura ligera y acabados exteriores.",
        "manual_step": "acabados_finales",
        "tags": "estructura ligera,acabados",
    },
    {
        "title": "House Renovation / Construction Timelapse – Construction of a home from start to finish",
        "category": "acabados",
        "youtube_id": "ftt-JWHI1Js",
        "level": "avanzado",
        "stage": "Acabados, pintura y techumbre",
        "description": "Timelapse que muestra acabados, impermeabilización y entrega final.",
        "manual_step": "acabados_finales",
        "tags": "acabados,impermeabilizacion",
    },
]


def main() -> None:
    database.init_db()
    with database.get_connection() as connection:
        connection.execute("DELETE FROM video_watch_history")
        connection.execute("DELETE FROM videos")
        for video in VIDEO_DATA:
            connection.execute(
                """
                INSERT INTO videos (title, category, youtube_id, level, stage, description, manual_step, tags)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    video["title"],
                    video["category"],
                    video["youtube_id"],
                    video["level"],
                    video["stage"],
                    video["description"],
                    video["manual_step"],
                    video.get("tags", ""),
                ),
            )
    print("Catálogo de videos actualizado correctamente.")


if __name__ == "__main__":
    main()
